import { useState } from "react";
import { formatBillingChf as chf } from "../shared/billing";

export type PostalRow={id:string;invoice_id:string;status:string;environment:string;provider_status:string|null;provider_address:string|null;
  quoted_cents:number|null;quote_token:string|null;quoted_at:string|null;approved_cents:number|null;send_started_at:string|null;create_started_at:string|null;cost_confirmed:boolean;last_error:string|null};
export type PostalCost={id:string;invoice_id:string;dispatch_id:string;amount_cents:number;booked_on:string;provider_letter_id:string;remaining_cents:string};
const labels:Record<string,string>={preparing:"Wird vorbereitet",validating:"Pingen prüft das PDF",ready:"Bereit zur Versandfreigabe",sending:"Versand wird übermittelt",
  submitted:"Versandauftrag angenommen",sent:"An die Post übergeben",delivered:"Zustellung bestätigt",undeliverable:"Unzustellbar",cancelled:"Bei Pingen storniert",needs_review:"Status prüfen"};
const errors:Record<string,string>={pingen_not_configured:"Der zentrale Pingen-API-Zugang fehlt noch.",pingen_postal_disabled:"Der Postversand ist noch nicht freigegeben.",pingen_production_only:"Echter Postversand ist nur auf der produktiven Website möglich.",
  pingen_quote_expired:"Bitte den Preis und Status aktualisieren und erneut prüfen.",pingen_quote_changed:"Der Pingen-Preis hat sich geändert. Bitte die neuen Kosten prüfen und erneut freigeben.",
  pingen_provider_review:"Pingen benötigt eine Prüfung. Bitte den Status aktualisieren und das Dokument im Pingen-Konto prüfen.",pingen_document_mismatch:"Pingen hat abweichende Dokument- oder Adressangaben erkannt. Es wird nichts versendet.",
  pingen_paper_not_ready:"Pingen hat das QR-Papier noch nicht bestätigt. Bitte den Status erneut aktualisieren.",pingen_recovery_required:"Der vorherige Upload ist noch nicht eindeutig zugeordnet. Bitte im zentralen Pingen-Konto prüfen; keinen zweiten Brief versenden.",
  pingen_prepare_again:"Der Upload wurde nicht abgeschlossen. Bitte erneut vorbereiten.",pingen_processing:"Die Übermittlung läuft noch. Bitte nach kurzer Zeit den Status aktualisieren.",
  pingen_invoice_received:"Zu dieser Rechnung liegt bereits eine Zahlung vor. Ein weiterer Rechnungsversand ist gesperrt.",pingen_address_invalid:"Für den Postversand wird eine vollständige Schweizer Postadresse benötigt.",
  pingen_account_changed:"Dieser Versandauftrag gehört zu einer anderen Pingen-Konfiguration. Bitte die Plattformverantwortung kontaktieren.",billing_source_unavailable:"Die Abrechnungsgrundlage wurde geändert oder storniert. Bitte zuerst die Rechnung prüfen."};

export function PostalManagement({tenantId,accountId,canWrite,enabled,environment,invoices,dispatches,costs,onChanged}:{tenantId:string;accountId:string;canWrite:boolean;enabled:boolean;environment:string;
  invoices:Array<{id:string;status:string;invoice_number:string|null;recipient:{name:string};sourceAvailable:boolean;received_cents:string}>;dispatches:PostalRow[];costs:PostalCost[];onChanged:()=>Promise<void>}) {
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[approved,setApproved]=useState<string|null>(null),[accepted,setAccepted]=useState(false);
  const run=async(path:string,body:object={})=>{setBusy(true);setError('');try{
    const response=await fetch(`/api/postal/${tenantId}/${path}`,{method:'POST',headers:{'Content-Type':'application/json','X-Sponsor-Account':accountId},body:JSON.stringify(body)});
    const result=await response.json();await onChanged();if(!response.ok)throw new Error(result.error??'pingen_request_uncertain');setApproved(null);setAccepted(false);
  }catch(reason){setError(errors[(reason as Error).message]??"Pingen konnte die Aktion nicht abschliessen. Bitte den Versandstatus aktualisieren. Ein unklarer Versand wird nicht automatisch wiederholt.");}finally{setBusy(false);}};
  const candidates=invoices.filter(invoice=>invoice.status==='issued'&&invoice.sourceAvailable&&Number(invoice.received_cents)===0&&!dispatches.some(row=>row.invoice_id===invoice.id&&row.environment===environment));
  return <section className="workspace-panel"><h2>Rechnungen per Post versenden</h2><p>Die Plattform bezahlt Pingen über ihr zentrales Konto. Die bestätigten Versandkosten werden dem Verein ohne zusätzlichen Versandaufschlag weiterverrechnet und von der monatlichen Auszahlung abgezogen. Der Sponsor bezahlt keine Versandkosten.</p>
    {environment==='staging'&&<p className="finance-warning">Testumgebung: Es werden keine echten Briefe verschickt und keine Versandkosten vom Vereinsguthaben abgezogen.</p>}
    {error&&<p className="form-error" role="alert">{error}</p>}
    {canWrite&&<form className="finance-create" onSubmit={event=>{event.preventDefault();if(selected)void run(`invoices/${selected}/prepare`);}}><label>Freigegebene, unbezahlte Rechnung<select required value={selected} onChange={event=>setSelected(event.target.value)}><option value="">Rechnung wählen …</option>{candidates.map(row=><option key={row.id} value={row.id}>{row.invoice_number} · {row.recipient.name}</option>)}</select></label><button className="access-secondary" disabled={busy||!enabled||!candidates.some(row=>row.id===selected)}>Bei Pingen vorbereiten</button><small>Das PDF wird zur Prüfung hochgeladen. Der kostenpflichtige Versand erfolgt erst nach Ihrer Freigabe.</small></form>}
    <div className="finance-table-wrap"><table className="finance-table"><thead><tr><th>Rechnung</th><th>Versandstatus</th><th>Versandkosten</th><th>Aktion</th></tr></thead><tbody>{dispatches.map(row=>{
      const invoice=invoices.find(item=>item.id===row.invoice_id),booked=costs.filter(cost=>cost.dispatch_id===row.id).reduce((sum,cost)=>sum+cost.amount_cents,0);
      return <tr key={row.id}><td><strong>{invoice?.invoice_number}</strong><small>{invoice?.recipient.name}</small>{row.environment==='staging'&&<small>Testversand</small>}</td><td>{labels[row.status]??'Status prüfen'}{row.provider_status&&<small>Pingen: {row.provider_status}</small>}{row.send_started_at&&!row.cost_confirmed&&<small>Kostenabgleich ausstehend</small>}</td><td>{row.environment==='production'&&row.cost_confirmed?<><strong>{chf(booked)}</strong><small>Bestätigte Kosten</small></>:row.quoted_cents!==null?<><strong>{chf(row.quoted_cents)}</strong><small>Kostenvorschau</small></>:'Noch nicht ermittelt'}</td><td>{canWrite&&row.environment===environment&&<><button disabled={busy} className="access-secondary" onClick={()=>void run(`dispatches/${row.id}/sync`)}>Preis / Status aktualisieren</button>{!row.create_started_at&&row.status==='needs_review'&&<button disabled={busy||!enabled} className="access-secondary" onClick={()=>void run(`invoices/${row.invoice_id}/prepare`)}>Upload wiederholen</button>}{row.status==='ready'&&!row.send_started_at&&<button disabled={busy||!enabled} className="access-primary" onClick={()=>{setApproved(row.id);setAccepted(false);}}>Versand prüfen</button>}</>}
        {approved===row.id&&<form onSubmit={event=>{event.preventDefault();void run(`dispatches/${row.id}/send`,{quoteToken:row.quote_token,quotedCents:row.quoted_cents,costsAccepted:accepted});}}><p><strong>Empfänger laut Pingen</strong></p><pre className="postal-address">{row.provider_address}</pre><p>{chf(row.quoted_cents??0)} · Schweiz, günstigste Versandart, einseitig, Graustufen, QR-Papier.</p><label className="finance-checkbox"><input type="checkbox" required checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>Ich habe PDF und Empfänger geprüft und gebe den Versand zu den angezeigten Kosten zulasten des Vereins frei. Der Abzug erfolgt bei der monatlichen Auszahlung.</span></label><button disabled={busy||!accepted} className="access-primary">{row.environment==='staging'?'Testversand auslösen':'Kostenpflichtig versenden'}</button><button type="button" className="access-secondary" onClick={()=>setApproved(null)}>Abbrechen</button></form>}</td></tr>;
    })}</tbody></table>{!dispatches.length&&<p>Noch keine Postversandaufträge.</p>}</div>
  </section>;
}
